baseURL:  https://cstrnull00.github.io/
title:  기타 의견 반려함
theme:  hextra
contentDir: "content"
timeZone: "Asia/Seoul"

outputs:
  home: [html, rss, json]

params:
  enableSearch: false
  favicon: favicon.ico
  navbar:
    logo:
      path: images/logo.png
      width: 32
      height: 32

menus:
  main:
    - name: "게임 리뷰"
      url: "/review/"
      weight: 2
    - name: "콘텐츠 분석"
      url: "/analysis/"
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true

enableGitInfo: true

ignoreFiles:
  - ".*glossary.*"